README.md, lib/pay/billable/stripe.rb
Found this little inconsistency in the README.
=> Update README to reflect recent changes

lib/pay/billable.rb, test/pay/billable_test.rb, test/support/schema.rb
Fixed a bug in on_trial? due to me adding named attributes in a previous
PR. Also made it so we return in the case of plan being nil.
cc: @excid3
=> Fix bug in on_trial? method

README.md, lib/generators/pay/email_views_generator.rb
Make it so you can copy the email views to your app if you want to customize them (https://github.com/jasoncharnes/pay/issues/34)
=> Added email views generator

app/models/concerns/pay/chargeable.rb, app/views/pay/user_mailer/receipt.html.erb, app/views/pay/user_mailer/refund.html.erb, test/pay/chargeable_test.rb, test/support/charge.rb, test/test_helper.rb
We might as well extract this to a method for reusability sake :)
That'll help us in the future when we have Paypal as well
=> Extracted charged to info to charged_to

README.md, app/jobs/pay/email_sync_job.rb, lib/pay/billable/sync_email.rb, test/jobs/pay/email_sync_job_test.rb, test/pay/billable/braintree_test.rb, test/pay/billable/stripe_test.rb
This moves the syncing of email changes -> processor to a background job.
=> Add EmailSyncJob

lib/pay/stripe/charge_refunded.rb
Just discovered this one :)
cc: @excid3
=> Changed charge.user -> charge.owner

README.md
=> document restart after gem installation

app/controllers/pay/webhooks/braintree_controller.rb, lib/pay/stripe/webhooks/charge_succeeded.rb, lib/pay/stripe/webhooks/customer_deleted.rb, lib/pay/stripe/webhooks/customer_updated.rb, lib/pay/stripe/webhooks/source_deleted.rb
There was an issue when using webhooks and a `billable_class` different than `User`.
=> Use Configured billable model instead of User. in webhooks

lib/generators/active_record/templates/migration.rb
fixes issue https://github.com/pay-rails/pay/issues/135
=> fix bad migration name

README.md
I'm currently going through the installation process and trying to update documentation according to actual behavior. 
Hopefully, this fixes #140
=> Updating docs to fill gaps for AddFieldsToBillable migration

db/migrate/20170205020145_create_pay_subscriptions.rb, db/migrate/20170727235816_create_pay_charges.rb
This pull request should overtake #162.
=> Add note that owner_id could be a string

lib/pay/paddle/webhooks/subscription_payment_succeeded.rb, test/pay/paddle/webhooks/subscription_payment_succeeded_test.rb
This PR adds paddle card or paypal details to pay charges.
=> Paddle payment details

docs/fake_processor.md
=> Fix typo in method

docs/Stripe-Elements-v3-SCA-Compatible.md
I move the page `Stripe Elements v3 SCA Compatible` from the Wiki to the docs and I updated it a bit.
=> Add Stripe Elements v3 SCA Compatible to docs

docs/1_installation.md, docs/2_configuration.md, docs/3_customers.md, docs/4_payment_methods.md, docs/5_charges.md
5 markdown links are 404, this PR fixes them.
=> Update docs (Fix links)

app/jobs/pay/customer_sync_job.rb, lib/pay/braintree/billable.rb, lib/pay/fake_processor/billable.rb, lib/pay/paddle/billable.rb, lib/pay/stripe/billable.rb, test/jobs/pay/customer_sync_job_test.rb
=> Add customer name & email sync to payment processors. Fixes #440

lib/pay/fake_processor/billable.rb, test/pay/fake_processor/subscription_test.rb
=> Fix fake processor trial days issue

docs/1_installation.md, lib/pay/attributes.rb, lib/pay/stripe/billable.rb, test/dummy/app/models/user.rb, test/pay/attributes_test.rb, test/pay/stripe/billable_test.rb
This PR allows full control over customer fields to be sent to Stripe.
Belongs to #250
=> Allow full control over customer fields in Stripe

UPGRADE.md, lib/pay/stripe/subscription.rb
This PR adds new information for updating from Pay 3.0 to the next major release of Pay.
=> update for 4.0

docs/stripe/3_javascript.md
Just wanted to make it more clear how to create a setup intent using `pay` and how to use it in this context.
=> Add in some documentation for SetupIntent

lib/pay/fake_processor.rb, lib/pay/fake_processor/merchant.rb
This PR adds Merchant to the Fake Processor so we can use it on our tests without breaking merchants.
It belongs to this issue #558.
If you could guide me on how can I improve this PR in order to merge. 
Thanks 🙌
=> Add Merchant to Fake processor

UPGRADE.md
This PR pulls in an example from #648 in order to be more explicit.
=> add param name change examples

docs/1_installation.md
Small versions update for recent v6 release.
=> Update gems for pay 6

README.md
Just a small fix for the recent v6 release.
=> Update Stripe API version for pay 6

CHANGELOG.md, app/models/pay/customer.rb
This PR removes unused attributes from the pay/customer model and provides updates for the changelog for this PR and PR #771
=> remove unused attributes in customer.rb. update changelog

app/views/pay/payments/show.html.erb
=> Fix stimulus import on payment page. Closes #812

docs/2_configuration.md
=> fix typo -- Update 2_configuration.md

docs/marketplaces/stripe_connect.md
This PR adds `current_user.set_payment_processor :stripe, stripe_account: "acct_1234"` for stripe market place session checkout.
=> Update Stripe Connect ReadMe 

lib/pay/paddle_classic/subscription.rb, lib/pay/paddle_classic/webhooks/subscription_cancelled.rb, test/pay/paddle_classic/subscription_test.rb, test/pay/paddle_classic/webhooks/subscription_cancelled_test.rb, test/test_helper.rb, test/vcr_cassettes/test_paddle_classic_cancel_with_future_ends_at.yml
…even though Paddle cancels them immediately
Fixes #888
=> Consider Paddle Classic cancellations as active until end of period

docs/2_configuration.md, docs/7_webhooks.md, docs/stripe/2_credentials.md, docs/stripe/5_webhooks.md, docs/stripe/8_stripe_checkout.md
**Summary:**
Doc improvements for Stripe so it is easier for newbies to follow instructions step by step and get the working configurations.
I have also added notes on how to enable webhooks in production which I myself had struggled a bit in the start.
While configuring webhooks in production / live app, I had struggled a bit because instructions were not clear enough on what to do and because I was completely new to Stripe. The purpose of this PR is to help anyone starting out to be able to setup everything correctly without having to search in the Internet.
P.S.: A lot of these contents are copied from Bullet Train docs: https://bullettrain.co/docs/billing/stripe
=> Stripe docs improvements

app/models/pay/paddle_billing/customer.rb
**Summary:**
Fix typo while creating new paddle_billing customer
=> Fix typo in paddle_billing customer api_record method

docs/1_installation.md
**Summary:**
Update installation docs to version 8
I was going through first time install and realized install docs pin to v7. A quick PR to update docs.
**Testing:**
**Checklist:**
=> Update installation docs to v8

README.md
**Summary:**
Just a small mention in the docs for a new provider for ASAAS (a brazillian payment gateway)
I added the mention in the README.md, but feel free to suggest or move it to a more appropriate section if needed. Thanks a lot for the gem!!
=> add Asaas provider to the README.md

docs/stripe/5_webhooks.md
**Summary:**
Fixed a typo in docs
=> Fixed typo

docs/6_subscriptions.md
**Summary:**
Just a small change to fix docs
Current documentation doesn't work - undefined method. Added the correct method.
=> Fix documentation for fetching API record from processor

docs/1_installation.md, docs/marketplaces/stripe_connect.md
**Summary:**
A few things spotted in the readmes
=> Fix readme
