pay-rails/pay

lib/pay/billable/stripe.rb
I'm pretty sure the Stripe::Customer object just has a `default_source` and not `default_source_id` per https://stripe.com/docs/sources/customers
It at least blows up in my app when trying to access `default_source_id` on `Stripe::Customer:
cc: @excid3
=> Change default_source_id->default_source on customer

lib/pay/stripe/subscription_renewing.rb, lib/pay/stripe/subscription_updated.rb
Updated subscription renewing/updated to match the new
processor/processor_id table layouts - as well as using `object.id` instead of `object.subscription.
cc: @excid3
=> Update subscription renewing/updated

app/mailers/pay/user_mailer.rb, app/views/pay/user_mailer/receipt.html.erb, app/views/pay/user_mailer/refund.html.erb, lib/pay.rb, test/mailers/pay/user_mailer_test.rb
I discovered some more issues with the mailers, the subject field appeared to be named `From` - and it appears that the column name on charge is `card_type` and on users it's `card_brand` - we probably want to be consistent here?
=> Fix some small mailer bugs

lib/pay/billable.rb, lib/pay/billable/braintree.rb, lib/pay/billable/stripe.rb, test/pay/billable/braintree_test.rb, test/pay/billable/stripe_test.rb
This should sync the local email changes to the payment processor if the user who's email got updated has any subscriptions.
@excid3 not sure if we want to do this in a background job instead?
=> Sync email changes to processor

lib/pay/billable.rb, test/pay/billable_test.rb, test/support/schema.rb
I think the logic in `on_generic_trial?` was wrong. This PR fixes that
cc: @excid3
=> Fix on generic trial

app/models/concerns/pay/chargeable.rb, test/pay/chargeable_test.rb
I introduced a pretty nasty bug when I tried to check for `Pay.config` attributes. I don't think I know ruby well enough to fix it - so let's just stop being this defensive for now and remove those checks.
cc: @excid3
=> Remove receipt_attributes check for now

.travis.yml
What do you think of testing against ruby 2.4.1, 2.5.3 and 2.6.0?
=> configure travis to test with ruby 2.4.1, 2.5.3 and 2.6.0

README.md, lib/pay/billable.rb, test/pay/billable_test.rb
Added a convenience method to billable that checks for either an active trial, or a subscription
=> Provide method that checks for active trial or subscription

app/models/pay/subscription.rb
When trying to add scopes to the `Team` class in jumpstart (but applicable in other scenarios) we run into ambiguous column error. This should remove that.
=> Get rid of ambiguous column with team based scopes.

lib/pay/billable/sync_email.rb
Otherwise you could queue up a job if the record isn't saved/created. This causes failures in Rails 6+.
=> Only queue the sync if the change is committed

app/views/layouts/pay/application.html.erb, app/views/pay/payments/show.html.erb
This prevents the payment intent confirmation page from "jumping" around as the Stripe modal appears/closes.
I believe the idea was to place the panel vertically central on the page, this pull request fixes it.
Alternatively, the main `application.html.erb` could be tweaked as it also has a few `h-full` css classes.
Rikki
=> Update pay confirmation page

db/migrate/20170727235816_create_pay_charges.rb, db/migrate/20190816015720_add_status_to_pay_subscriptions.rb
I'm currently integrating into a Rails 5.0 app.  The README mentions that Rails 4.2 and above is supported.
However running the migrations gives `ArgumentError: Unknown migration version "5.1"; expected one of "4.2", "5.0"` since two fo the migrations are targeted to `5.1` and `5.2`
I didn't notice anything 5.x specific in the migrations, so changed their version number to support 4.2
=> Allow running migration on Rails 4.2

lib/pay/env.rb
If running on Rails < 5.2, then `credentials` does not exist on `Rails.application`.  Added code to tolerate this.
=> Handle no `credentials` on Rails < 5.2

app/models/pay/subscription.rb
When resuming a subscription that's on a grace period, the status stays `canceled`.
This will set the status back to active when resuming.
=> Sets status back to active when resuming a subscription

app/models/pay/subscription.rb
This adds the scope specificity back in that was introduced in
2f61c38f7c8a55a03d1a3b7ea0f1e4d504a4d73f but lost in 89c590cbbd21c2120ff35b60a75410a10e268fdc.
Originally committed by: @caseyprovost
Related: #94
=> Fix subscription status scopes

lib/pay/stripe/billable.rb
Generally the payment method ID returned from Stripe::PaymentMethod.attach should match the `card_token` passed into this method however this is not the case when using Stripe test payment tokens (e.g. `pm_card_visa`) - these virtual tokens create a copy of that test card attached to the customer with a new, unique ID. 
Trying to set `invoice_settings.default_payment_method` to the virtual payment method ID subsequently fails as the customer does not have a payment method with that ID. As is done in `update_stripe_card`, the returned payment method ID should be used instead.
I ran into this bug trying to write some integration tests against a Stripe test account (I know automated tests should not generally hit the API, I do plan to swap in a fake server or VCR once I've got them working …
=> Use Stripe payment method ID when setting default

app/mailers/pay/user_mailer.rb
Fixes https://github.com/pay-rails/pay/issues/148
The user mailer was incorrectly looking for the `name` attribute but the [billable](https://github.com/pay-rails/pay/blob/master/lib/pay/billable.rb#L45) model only has a `customer_name` attribute.
=> Udpate name to customer_name in useer mailer

lib/pay/braintree.rb
does this need to be `Pay::Braintree::Billable` instead?
=> potential error in Brainstree#set_up

app/controllers/pay/payments_controller.rb, app/views/pay/payments/show.html.erb
Currently the "Go back" button is linked to `root_path`. This PR allows a `?back=/path/to/item` attribute to be provided to the `/payments/pi_xyz?back=%2Fpath` URL
=> Allow pay 'Go back' button to be configured via ?back=/path/to/item

lib/pay/billable.rb, test/dummy/db/schema.rb, test/pay/billable_test.rb, test/pay/chargeable_test.rb
Before the change, `as: :owner` was missing from the relations from a billable to charges and subscriptions defined when including Billable into a model.
When two billables from different models had the same id, querying from one of them could return the subscriptions or charges from the other.
Fixes #207
=> Fix polymorphic querying for charges and subscriptions

README.md
I did not find this in the documentation so checked the source code and added to readme
=> docs: add event types for stripe webhook

lib/pay/stripe/billable.rb
Stripe::Customer objects now have a name field.
This pull request changes storing the customer name from the customer description to name.
=> Update customer create to use new stripe name column

lib/pay.rb
=> Fix typo in error message

lib/pay/stripe/webhooks/subscription_created.rb
When the `customer.subscription.created` event is triggered in Stripe, the subsequent Pay webhook fails when it cannot find an existing subscription and tries to create a new one.
Initialize `Pay.subscription_model` with the required attribute values.
Resolves #184
=> Initialize Subscription with required values (Stripe Webhook)

lib/pay/paddle/billable.rb, lib/pay/paddle/webhooks/subscription_payment_succeeded.rb, test/pay/paddle/billable_test.rb, test/pay/paddle/webhooks/subscription_payment_succeeded_test.rb
Synchronizes the current payment information from paddle for billable models.
The sync can be triggered manually with `billable.sync_payment_information_from_paddle` or the current payment infos will be also updated by the payment succeeded webhook.
=> Sync current payment information from paddle

README.md, lib/pay.rb, lib/pay/billable.rb, lib/pay/paddle/webhooks/subscription_created.rb, lib/pay/stripe/webhooks/subscription_created.rb, test/pay_test.rb
Adds options to configure the default names for product/plan.
closes #220
=> Configurable default names - Product/Plan

lib/pay/stripe/subscription.rb, test/models/subscription_test.rb
I found this bug in my own test suite. It was just a missed delegation. This should also fix bugs in resuming and swapping trialing subscriptions since they also reference `trial_ends_at`.
=> Fix no method error when cancelling trialing subscription

CHANGELOG.md, README.md, docs/fake_processor.md, lib/pay.rb, lib/pay/billable.rb, lib/pay/fake_processor.rb, lib/pay/fake_processor/billable.rb, lib/pay/fake_processor/charge.rb, lib/pay/fake_processor/error.rb, lib/pay/fake_processor/subscription.rb, test/pay/fake_processor/billable_test.rb, test/pay/fake_processor/charge_test.rb, test/pay/fake_processor/subscription_test.rb
This provides a fake payment processor that can be used for testing and for giving users a free subscription to your app.
You'll want to be careful not to allow someone to subscribe with `fake_processor`. We'll probably want to add a validation to Billable so that `fake_processor` isn't allowed unless explicitly enabled.
*Update* Added a fake processor flag and validation so users can't set this maliciously from the frontend.
=> Add fake processor for testing and internal use

README.md
When apps have a Content Security Policy in place, the domains for the Stripe and Vue scripts, styles and frames should be added to the CSP in order for the payment confirmation pages to work.
Having this note in the README would be helpful in avoiding problems after deployment
=> Add CSP note to Stripe SCA Payment confirmations

app/views/pay/stripe/_checkout_button.html.erb
Just above this function, the div to display errors has a different id, which will be fixed by this update.
=> Fix error div Id reference

lib/pay/paddle.rb, lib/pay/paddle/webhooks/subscription_created.rb, lib/pay/paddle/webhooks/subscription_payment_succeeded.rb
In my staging tests I realized that although the payment succeeded webhook is fired after the subscription created webhook, it is possible that the payment succeeded webhook is handled first. That means it is not guaranteed that there is already a paddle processor id saved in the database.
For this scenario the billable should be extracted from the passthrough parameter (similar to the subscription created webhook).
=> Add passthrough fallback for paddle payment succeeded webhook

lib/pay/stripe/billable.rb
=> Don't call route helpers unless needed for Stripe Checkout

lib/generators/active_record/templates/migration.rb, test/dummy/db/migrate/20200603150703_add_pay_billable_to_users.rb, test/dummy/db/migrate/20200603152357_add_pay_billable_to_teams.rb
As I was running these migration on my personal project, I've noticed that `change_table` is being run without `bulk: true`. Without that flag, all the new columns would be added one by one, which can be significantly slower on large tables. Instead, this will group them into one SQL query.
References:
- https://aaronlasseigne.com/2012/06/05/faster-activerecord-migrations-using-change-table-bulk/
- https://blog.toshima.ru/2020/01/02/rails-migration-bulk-true.html#migration-with-bulk-option
- https://makandracards.com/makandra/3303-bulk-change-multiple-table-rows-in-a-migration
=> Use bulk: true when running change_table migrations

README.md
both pay_subscriptions and pay_charges need a little tweak as commented in the related migrations (*_create_pay_subscriptions.pay.rb, *_create_pay_subscriptions.pay.rb) :
```
t.references :owner, polymorphic: true
```
=> add README note on owner_id column format

lib/pay/stripe.rb, lib/pay/stripe/billable.rb, lib/pay/stripe/charge.rb, lib/pay/stripe/subscription.rb, lib/pay/stripe/webhooks/charge_refunded.rb, lib/pay/stripe/webhooks/charge_succeeded.rb, lib/pay/stripe/webhooks/checkout_session_async_payment_succeeded.rb, lib/pay/stripe/webhooks/checkout_session_completed.rb, lib/pay/stripe/webhooks/payment_intent_succeeded.rb, lib/pay/stripe/webhooks/subscription_created.rb, lib/pay/stripe/webhooks/subscription_deleted.rb, lib/pay/stripe/webhooks/subscription_renewing.rb, lib/pay/stripe/webhooks/subscription_updated.rb, test/pay/billable/stripe_test.rb, test/pay/stripe/charge_test.rb, test/pay/stripe/subscription_test.rb, test/pay/stripe/webhooks/charge_refunded_test.rb, test/pay/stripe/webhooks/charge_succeeded_test.rb, test/pay/stripe/webhooks/subscription_created_test.rb, test/pay/stripe/webhooks/subscription_deleted_test.rb, test/pay/stripe/webhooks/subscription_renewing_test.rb, test/pay/stripe/webhooks/subscription_updated_test.rb, test/pay/webhooks/delegator_test.rb, test/support/fixtures/stripe/charge_succeeded_event.json
Since webhook order is not guaranteed, we can simply use the webhooks as a trigger to query the latest information from the API. That way webhooks can arrive out of order, but we won't be saving stale data.
=> Refactor webhooks

lib/pay/stripe/billable.rb
Hi, 
I'm getting going with pay-rails and stripe, and Stripe's lack of any accountability for its webhooks arriving at all, or in the correct order, or... well really anything, is making me just a touch nervous.  In development particularly their webhooks completely miss the stripe local server, leading to odd out of sync states.
So here's a little api wrapper that resyncs all of a stripe customer subscriptions.  Unfortunately I don't see a way to map a stripe price_id for the subscription back to a rails-pay `name` -- not sure if I'm missing somewhere where a mapping should be registered?  Nor do I have necessarily have the bandwidth to go figure out the other payment processors.
But I found this useful.  yeah.
=> RFC: add a path for syncing all of a customer's subscriptions

lib/pay/stripe/subscription.rb, test/pay/stripe/subscription_test.rb, test/pay/stripe/webhooks/subscription_updated_test.rb
pulling in v2.7.1 to my code.  There's a problem with processing stripe subscriptions that are Renewed after a user cancels them -- because of the way the sync logic worked we weren't properly bringing them "back from the dead".
There's a lot of different fields in the slack api around subscriptions ending/cancelling/etc -- I'm not sure I understand them all, so I hope I'm getting this right.  I'm honestly coding just a little blind. 
It also feels as though we could *probably* just trust the `cancel_at` field in the slack api (without bothering with `cancel_at_period_end` etc) but again I'm not super-familiar with the intimates of the api.
=> Properly process subscription renewels from stripe

lib/pay/stripe/billable.rb, lib/pay/stripe/charge.rb, lib/pay/stripe/subscription.rb, test/pay/billable_test.rb
This removes warning of nil header from net/http and fixes a couple references that didn't include the stripe account.
=> Extract stripe options hash and compact to remove nils

lib/pay/payment.rb, lib/pay/stripe/billable.rb
Trialing subscriptions don't require a PaymentMethod, so validating the associated SetupIntent is unnecessary.
=> Don't validate SetupIntent for trialing subscription

app/models/pay/subscription.rb, lib/pay/attributes.rb, test/models/pay/subscription_test.rb, test/pay/stripe/subscription_test.rb
@excid3 before I get too far, I want to make sure I'm going in the right direction. I wrote a failing test as a guide.
**Questions**
- Should I even be concerned about when the `Owner` is deleted, or is it enough to just test when the `Pay::Customer` is deleted?
- Should the test be in the Subscription namespace for each Payment Processor namespace? Or should it be in `Pay::Billable::SyncCustomer::Test`?
=> Cancel active subscriptions when Owner is deleted

app/models/pay/charge.rb, app/models/pay/customer.rb, app/models/pay/subscription.rb, test/models/pay/charge_test.rb, test/models/pay/customer_test.rb, test/models/pay/subscription_test.rb
Now that we're soft deleting `Pay::Customer` records I figured it might be helpful to add some scopes on the `Pay::Charge` and `Pay::Subscription` models. This way one could query for records that are tied to a deleted customer. 
```ruby
Pay::Charge.with_active_customer
Pay::Charge.with_deleted_customer
Pay::Subscription.with_active_customer
Pay::Subscription.with_deleted_customer
```
Also, add helper methods to `Pay::Customer`
```ruby
Pay::Customer.first.active?
Pay::Customer.first.deleted?
```
=> Add scopes to Pay::Charge and Pay::Subscription to account for Pay::Customer deleted_at column 

docs/stripe/1_overview.md
I _think_ the currently documented syntax is from Pay2, while Pay3 has subtly updated the syntax to no longer be an assignment to `processor`, but instead an argument passed to `set_payment_processor`. Is that right?
=> Correct syntax for setting `payment_processor`

app/models/pay/customer.rb, test/pay/billable_test.rb
In order to allow setting a specific name to be used as the
`pay_customer_name`, check for the existance of `pay_customer_name` on
the `owner` and use that if present. Else, try `name` and then
`first_name` + `last_name` as before.
=> Use `pay_customer_name` if available

db/migrate/20210714175351_add_uniqueness_to_pay_models.rb
```
rake aborted!
ArgumentError: Unknown migration version "6.1"; expected one of "4.2", "5.0", "5.1", "5.2"
```
Fix Rails 6.1 reference in 2.x when using in <6 Rails app
=> fix 6.1 rails reference in 2.x

docs/stripe/1_overview.md
Looks like a typo, thanks for the excellent work with `pay` ✨
=> Remove duplicated "cancel" URL reference

UPGRADE.md
Added 4 add_column in the self.down of the migration UpgradeToPayVersion3
Without them, the rollback is not complete and would block migrating again as those 4 columns have a remove_column in the migration.
=> Update UPGRADE.md (migration update)

test/dummy/app/controllers/stripe/charges_controller.rb
Something I noticed when looking through the dummy app. I haven't actually used `binding.irb` before, but my impression is that it's a debugging statement similar to pry's `binding.pry` so I assume it just got left in by accident.
=> Remove binding.irb statement in dummy app

docs/stripe/1_overview.md, lib/pay/stripe/billable.rb
Removes hard coded `payment_method_types` to enable automatic payment methods to be surfaced in Checkout based on the Stripe Dashboard configuration. 
`payment_method_types` can still be passed in, but this will increase conversion by default by accepting more payment methods.
Helps address #376
=> Enable automatic payment methods for Stripe Checkout

lib/pay/billable/sync_customer.rb, test/pay/billable/sync_customer_test.rb
Before this change it was possible to trigger the `enqeue_sync_email_job` method by changing the
`pay_should_sync_customer?` but the method would be a no-op unless the email changed.
This pull request makes it possible for someone to override _when_ the customer would be synced by overriding the `pay_should_sync_customer?` method.
The idea behind this is that the customer's `name` will also be synced to Stripe when they change it in our app. We would achieve this by adding this to `models/user.rb`:
```ruby
def pay_should_sync_customer?
saved_change_to_email? || saved_change_to_name?
end
```
=> Allow syncing customers by overriding `pay_should_sync_customer?`

CHANGELOG.md, docs/1_installation.md, lib/pay/attributes.rb, lib/pay/stripe/billable.rb, test/dummy/app/models/user.rb, test/pay/attributes_test.rb, test/pay/stripe/billable_test.rb
Adds the ability to define a symbol or Proc that returns metadata when creating a Customer object in Stripe. This is named `metadata` currently, so if other payment processors support metadata, it can be included in those. Currently, Stripe is the only one that implements this afaik.
```ruby
class User < ApplicationRecord
pay_customer metadata: :stripe_metadata
def stripe_metadata
{ user_id: id }
end
end
```
Closes #431
=> Include metadata when creating customer in Stripe

CHANGELOG.md, lib/pay/attributes.rb, test/pay/attributes_test.rb
This adds the ability to define a default payment processor for a model. If you know you're going to use Stripe, then you can set it as the default and skip the `set_default_payment_processor` call.
```ruby
class User < ApplicationRecord
pay_customer default_payment_processor: :stripe
end
pay_customer = User.create(...).payment_processor
pay_customer.processor #=> "stripe"
```
Closes #518
=> Add default payment processor option

config/routes.rb
This commit only declare payment processor webhook route for installed ones, preventing from having unused webhook routes.
=> Updates webhook routes declaration

config/routes.rb, lib/pay.rb, lib/pay/braintree.rb, lib/pay/engine.rb, lib/pay/paddle.rb, lib/pay/stripe.rb, test/pay_test.rb
This PR allows for explicitly setting the payment processors to be used via an enabled_processors config variable. It also creates new class methods for `Pay::Stripe`, `Pay::Braintree`, and `Pay::Paddle` to check if they are enabled and of a compatible version. These methods are used to set up the processors and  the webhook routes if enabled.
=> fixes #456 - Allow enable and disable of processors

docs/2_configuration.md
This PR adds documentation for configuring the enabled_processors config var. If your application already has one of the default processors that Pay uses, you can omit it from being set up by Pay by not including it in the `config.enabled_processors` array.
=> add documentation for configuring the enabled_processors var

CHANGELOG.md, app/mailers/pay/user_mailer.rb, app/views/pay/user_mailer/receipt.html.erb, app/views/pay/user_mailer/refund.html.erb, docs/2_configuration.md, lib/pay.rb, lib/pay/braintree/webhooks/subscription_charged_successfully.rb, lib/pay/braintree/webhooks/subscription_trial_ended.rb, lib/pay/paddle/webhooks/subscription_payment_refunded.rb, lib/pay/paddle/webhooks/subscription_payment_succeeded.rb, lib/pay/paddle/webhooks/subscription_updated.rb, lib/pay/stripe/webhooks/charge_refunded.rb, lib/pay/stripe/webhooks/charge_succeeded.rb, lib/pay/stripe/webhooks/payment_action_required.rb, lib/pay/stripe/webhooks/subscription_renewing.rb, test/mailers/pay/user_mailer_test.rb, test/pay_test.rb
fixes #234 - This PR allows for the independent configuration of all emails sent out by Pay. These can be configured with a boolean value or a lambda.
=> allow independent configuration for each email

app/mailers/pay/application_mailer.rb
If the pay support_email isn't set, use the applications ActionMailer default from email address instead.
=> update mailer to pull ActionMailer default from email address

app/models/pay/charge.rb, docs/5_charges.md, lib/pay/stripe/charge.rb, test/pay/stripe/charge_test.rb, test/support/fixtures/stripe/charge.succeeded.json
This adds the receipt url provided by the Stripe API Charge object to Pay's Charge model in a similar fashion to the existing `paddle_receipt_url`
=> Add stripe receipt url to charge

CHANGELOG.md, app/models/pay/charge.rb, lib/pay/stripe/billable.rb, lib/pay/stripe/charge.rb, test/pay/stripe/billable_test.rb, test/pay/stripe/charge_test.rb, test/support/fixtures/stripe/charge.refunded.json, test/support/fixtures/stripe/charge.succeeded.json, test/vcr_cassettes/test_stripe_can_authorize_a_charge.yml, test/vcr_cassettes/test_stripe_can_capture_an_authorized_charge.yml
This adds two methods for authorizing and capturing charges with Stripe. Behind the scenes it uses payment intents, so we now record those as well.
=> Separate authorize and capture support for Stripe. Closes #457

docs/6_subscriptions.md
When using `#subscribed?` as documented:
```
@user.payment_processor.subscribed?(name: "default", plan: "monthly")
/gems/pay-b17b4ba767fd/app/models/pay/customer.rb:43:in `subscribed?': unknown keyword: :plan (ArgumentError)
```
The keyword looks to be `processor_plan` for `Pay::Customer#subscribed?` and `Pay::Customer#on_trial_or_subscribed?`.
https://github.com/pay-rails/pay/blob/b17b4ba767fdeaf60f5ddb690279bd7b05c28dc7/app/models/pay/customer.rb#L43-L46
https://github.com/pay-rails/pay/blob/b17b4ba767fdeaf60f5ddb690279bd7b05c28dc7/app/models/pay/customer.rb#L55-L58
```
@user.payment_processor.subscribed?(name: "default", processor_plan: "monthly")
false
```
=> Update docs to use processor_plan keyword for subscribed? methods

docs/1_installation.md
This **very minor** 😅 PR updates the version in the installation docs to v5.0, otherwise it fails when using v4.0 + Stripe v7:
``` sh
$ bin/rails pay:install:migrations
rails aborted!
[Pay] stripe gem must be version ~> 6
.../config/environment.rb:7:in `<main>'
Tasks: TOP => railties:install:migrations => db:load_config => environment
(See full trace by running task with --trace)
```
=> Update installation doc to v5

docs/6_subscriptions.md
A simple change here. Removing the word 'for' as 'with' was already present and makes more sense in the context.
=> add clarity by removing extra word

lib/pay/stripe/subscription.rb, test/pay/stripe/subscription_test.rb
While debugging some bugs in our app, we arrived this piece of code when syncing a subscription:
https://github.com/pay-rails/pay/blob/4c60f16da2a446ecf0bc40b025d2a8f9a4dc7057/lib/pay/stripe/subscription.rb#L46-L49
This is a somewhat recent addition from https://github.com/pay-rails/pay/commit/ed10e864503a364f1e0f17355a7094f89579dea2, due to fix issue https://github.com/pay-rails/pay/issues/601.
However, I'd like to propose this to be reconsidered; I think the correct logic here should be:
1. If a subscription is being canceled BEFORE trial_ends_at, then yes, the current behavior is desired (trial_ends_at should be set to match the subscription's ends_at); afterall, if you cancel a subscription during the trial period, the trial period is ending at that same instant as well; so, we're …
=> Fix trial_ends_at being set to the subscriptions cancellation time when the cancellation happens after the end of the trial

UPGRADE.md, db/migrate/1_create_pay_tables.rb, lib/pay/stripe/subscription.rb, test/dummy/db/schema.rb, test/pay/stripe/subscription_test.rb
This adds support for storing and reading `current_period_start` and  `current_period_end` on Stripe subscriptions. This is based on discussion https://github.com/pay-rails/pay/discussions/693.
Hoping to get feedback on this initial implementation.
- How do this Stripe implementation look?
- Is this how you would expect to handle the upgrade / db migration (i.e. just update `1_create_pay_tables.rb` directly and include a migration script in the upgrade documentation?)
- Tests sufficient?
- Would you want to add support for this in `fake_processor`?
- I'm not familiar with Braintree or Paddle but can look into it if you think it is required and no one else is available to.
Thanks!
=> Add current_period_start and current_period_end to Stripe subscriptions

lib/pay/billable/sync_customer.rb
`SyncCustomer`'s concern uses an `after_update` callback to sync the customer with the Payment Processor by enqueuing a `CustomerSyncJob`.
This simple PR changes this callback to an `after_commit`. Using an `after_update` here is not recommended for two reasons:
1. If the update's transaction rollbacks for any reason, the job will have be queued already, calling the external API, which is undesired;
2. Sometimes the background processing pipeline is so fast it will process the job even before the transaction is commited; this happens often and is [documented in Sidekiq's wiki](https://github.com/mperham/sidekiq/wiki/Problems-and-Troubleshooting#cannot-find-modelname-with-id12345); we should prefer to only enqueue the job after the transaction commited, so Sidekiq is guaranteed to lookup …
=> Change SyncCustomer after_update to after_commit

test/pay/stripe/webhooks/subscription_trial_will_end_test.rb
The tests for the trial will end need to run at a certain time always so that they do not break as time moves forward. I should've caught this sooner, my apologies!!! 😅
=> call travel_to to ensure the future doesn't break these tests

test/dummy/config/application.rb
Fixes this deprecation warning that is being triggered when running tests
@andrewmcodes
@xspynks
@Eduardo06sp
@cjilbert504
=> Remove deprecation warning for legacy connection handling

lib/pay/stripe/charge.rb
The default refund description was using the wrong key (`refund` instead of `pay.refund`). That caused the default refund description to be `translation missing: en.refund` and was viewable in Stripe's refund emails (and probably other places).
=> Fixes localization of the default refund description

docs/1_installation.md
This PR adds a link to Stripe API documentation for the Customer object so that users of Pay can easily find what additional attributes are allowed to be sent to Stripe.
=> add reference to Stripe docs for customer object attributes

docs/7_webhooks.md
Should declare class before referencing it
Co-authored-by: kaspth hey@kaspth.com
=> Fix NameError

lib/pay/braintree/subscription.rb, lib/pay/braintree/webhooks/subscription_canceled.rb, lib/pay/braintree/webhooks/subscription_expired.rb, lib/pay/braintree/webhooks/subscription_trial_ended.rb, lib/pay/braintree/webhooks/subscription_went_active.rb, lib/pay/braintree/webhooks/subscription_went_past_due.rb, test/pay/braintree/subscription_test.rb, test/pay/braintree/webhooks/subscription_canceled_test.rb, test/pay/braintree/webhooks/subscription_trial_ended_test.rb, test/vcr_cassettes/test_braintree_sync_active_subscription.yml, test/vcr_cassettes/test_braintree_sync_canceled_subscription.yml, test/vcr_cassettes/test_braintree_sync_canceled_subscription_with_trial.yml, test/vcr_cassettes/test_braintree_sync_subscription_with_trial.yml
This adds a `sync` method to the Braintree Subscription class.
Also changes Braintree subscriptions webhooks to sync instead of immediately operating on the subscription. This should make it more reliable in case webhooks arrive out of order, etc.
=> Add braintree subscription sync method

app/models/pay/customer.rb
When a project uses UUIDs for the table ids (`create_table "pay_subscriptions", id: :uuid, default: -> { "gen_random_uuid()" }, force: :cascade do |t|`), the current method of sorting the subscriptions by id will cause issues. 
For example, I have two subscriptions... Subscription 1 (has a uuid id of "942c38ef-b0df-43ac-bd85-f37d87efa643") was canceled. Subscription 2 (has a uuid of "0dca7550-ca58-49c2-87e1-2917e4e373f5") is active.
Subscription 2 should be returned when `.subscription` is called, but because the sort is id: :desc, it's returning Subscription 1.
IRB snippets:
```
irb(main):059:0> u.payment_processor.subscriptions
Pay::Subscription Load (9.3ms)  SELECT "pay_subscriptions".* FROM "pay_subscriptions" WHERE "pay_subscriptions"."customer_id" = $1  [["customer_id", …
```
=> Sort subscriptions by created_at instead of id, to work with uuids.

lib/pay.rb
This PR adds resolution to `Mail::Address` as a top level constant to avoid any confusion about this constant belonging under the `Pay` namespace.
Closes #770
=> add scope resolution operator to calls to Mail::Address

docs/stripe/8_stripe_checkout.md
`pay_name` override should be inside metadata. See https://github.com/pay-rails/pay/issues/562#issuecomment-1064142965
=> Update Stripe checkout docs

docs/6_subscriptions.md
This PR updates the Paddle checkout example in the documentation to produce a valid hyperlink - the current example doesn't have a closing `</a>` tag or any text.
=> Fix example link in Paddle passthrough example

.gitignore, lib/pay/fake_processor/billable.rb, test/dummy/config/application.rb, test/models/pay/customer_test.rb, test/pay/fake_processor/billable_test.rb
Adds support for…
* arbitrary arguments can be passed to `Pay::FakeProcessor::Billable#update_customer!`
* adds support for `promotion_code` to `Pay::FakeProcessor::Billable#subscribe`
=> Fake processor subscriptions

lib/pay/fake_processor/subscription.rb
I think we missed adding this delegation in a previous commit, this PR addresses that issue.
=> delegate ends_at? to pay_subscription

lib/pay/fake_processor/subscription.rb, lib/pay/paddle/billable.rb, test/pay/paddle/billable_test.rb
This resolves an issue that a customer raised in the JSP discord channel around not providing the keyword arg needed to be consistent with the `Pay::Paddle::PaymentMethod::sync` method. 
To read more detail about the issue follow this [link](https://discord.com/channels/874684608686477352/1113960193940803635)
=> Paddle update payment method

docs/stripe/9_customer_reconciliation.md
* Provides details on how to manually reconcile existing Stripe customers with Pay's customer records.
* Provides examples on how to automatically reconcile Stripe customers with Pay's customer records using ActiveRecord callbacks.
* Describes how to backfill subscriptions and charges for reconciled customers.
=> Adds documentation related to Stripe customer reconciliation (resolves #831)

docs/2_configuration.md, lib/pay/env.rb, test/pay/stripe_test.rb
Remove usage of deprecated Rails.applications.secrets
```
DEPRECATION WARNING: `Rails.application.secrets` is deprecated in favor of `Rails.application.credentials` and will be removed in Rails 7.2. (called from secrets at /Users/hac/.rvm/gems/ruby-3.2.2@railsdevs.com/gems/pay-6.6.1/lib/pay/env.rb:43)
```
=> Removed references to Rails.applications.secrets

docs/stripe/9_customer_reconciliation.md
Update documentation for reconciling stripe customer subscriptions
If you prefer to update the documentation, choose this PR. 
If you prefer to make the original method call available, [choose this other one](https://github.com/pay-rails/pay/pull/840).
=> Update documentation for reconciling stripe customer subscriptions

CHANGELOG.md, lib/pay/stripe/charge.rb, lib/pay/stripe/payment_method.rb, lib/pay/stripe/subscription.rb, test/pay/stripe/charge_test.rb, test/pay/stripe/payment_method_test.rb, test/pay/stripe/subscription_test.rb
This fixes a situation where `object.customer: null` and Pay returns a `Pay::Customer` where `processor_id: null`. Pay should be skipping these objects instead of associating them with a Pay::Customer.
=> Skip sync if object.customer is blank. Fixes #842

docs/1_installation.md
The docs still refer to v8 whereas the gem enforces v9
=> Updates Stripe gem version in the docs

lib/pay/stripe.rb, test/pay/stripe_test.rb
I've been trying to integrate the Stripe pricing table without success. I realized that the current method `Pay::Stripe.to_client_reference_id` is creating an invalid string. It includes a forward slash (like `User/42`), which isn't allowed according to Stripe's docs:
> The <stripe-pricing-table> web component supports setting the client-reference-id property. When the property is set, the pricing table passes it to the Checkout Session’s [client_reference_id](https://stripe.com/docs/api/checkout/sessions/object#checkout_session_object-client_reference_id) attribute to help you reconcile the Checkout Session with your internal system. This can be an authenticated user ID or a similar string. client-reference-id can be composed of **alphanumeric characters, dashes, or underscores**, and be …
=> Fix invalid client_reference_id composition

db/migrate/1_create_pay_tables.rb
Closes https://github.com/pay-rails/pay/issues/849
This PR modifies the `pay_customer_owner_index` index to rely on 3 columns instead of 4, so that migrations pass for people using the `strong_migrations` gem. I've also made this index unique as per [Chris's comment](https://github.com/pay-rails/pay/issues/849#issuecomment-1739146919).
Here's the explanation as to why one should [keep non-unique indexes to three columns or less](https://github.com/ankane/strong_migrations#keeping-non-unique-indexes-to-three-columns-or-less)
=> Fix for `strong_migrations`

app/models/pay/merchant.rb, test/models/pay/merchant_test.rb
This PR ensures we return a proper boolean value when `Pay::Merchant.data` is nil.
Also updated the tests to describe the expected return value.
=> Make sure onboarding_complete? returns a boolean value

.github/workflows/ci.yml
I saw that the master branch was renamed to main, so this PR updates the GH Actions workflow
=> Update GitHub Actions to use main branch

lib/pay/paddle/charge.rb
While working on updating the docs, I found that Charges weren't being created for transactions such as updating the subscription plan.
This PR updates the payment details to only be updated if there is a `payment`.
=> Fix issue with Paddle Billing Charges when there's no payment details

UPGRADE.md, docs/2_configuration.md, docs/6_subscriptions.md, docs/paddle_billing/1_overview.md, docs/paddle_billing/2_javascript.md, docs/paddle_classic/1_overview.md, lib/pay/paddle_billing.rb
Paddle have recently added [client side tokens](https://developer.paddle.com/changelog/2023/client-side-tokens) as a way to interact with the Paddle API using Paddle.js without exposing your API tokens. Paddle recommend using these instead of passing the `seller` option, as new features may require it. 
The latest feature of Paddle.js is the ability to [generate localised price previews](https://developer.paddle.com/changelog/2023/paddle-js-pricing-pages) on the fly, which is great for building pricing pages as it shows the customer's local currency (with taxes too). This was a feature I've been requesting since the start as the previous version had it too.
This PR adds `client_token` to `PaddleBilling`, which is set by environment variables or in the credentials/secrets files. 
I've also …
=> Paddle Billing Client Tokens & docs tweaks

lib/pay/paddle_billing/billable.rb, lib/pay/paddle_billing/subscription.rb
The paddle gem accept the option `extra` when retrieving a subscription.
See: https://github.com/deanpcmad/paddle/blob/83120a9e285cfb5daf36f7f56939e985ab029843/lib/paddle/models/subscription.rb#L11
What this PR allows us to do:
```ruby
subscription.processor_subscription(extra: 'next_transaction')
```
=> Retrieve paddle subscription with options

lib/pay/stripe/charge.rb, lib/pay/stripe/payment_method.rb
I wasn't able to test this fix with BLIK payments on my account, but this should safely handle any payment methods that don't provide additional details.
@WozniakMac give this a try and see if it fixes your issue?
=> Safely handle Stripe payment methods without extra details

docs/1_installation.md
Simple change to update the Readme docs so new users install the latest version of Pay (v7)
=> Fix: update pay gem version to 7

lib/pay/paddle_billing/subscription.rb, lib/pay/paddle_classic/subscription.rb
This fixes an issue with Paddle Classic where a subscription is synced after becoming `active` after `trialing` and the `trial_ends_at` time is not cleared.
=> Clear trial end when subscription becomes active

docs/1_installation.md
The example in the documentation for passing a lambda to `:stripe_attributes` had a syntax error: an improperly nested curly brace in the hash definition (just a curly brace out of place, really)
=> Fix syntax error in lambda for `stripe_attributes` in docs example

lib/pay/paddle_billing/payment_method.rb
Paddle have added a new `payment_method_id` field, which returns a Paddle ID. This replaces the `stored_payment_method_id` field which returned a UUID.
For their changelog entry: https://developer.paddle.com/changelog/2024/payment-method-paddle-id
I assume this means they will be adding a Payment Methods API soon, which could be useful.
=> Update Paddle Billing Payment Methods to use `payment_method_id`

test/mailers/previews/pay/user_mailer_preview.rb
**Summary:**
This PR fixes the `refund` preview calling `receipt` method on the UserMailerPreview
=> Fixes refund mailer preview rendering receipt

.devcontainer/Dockerfile, .devcontainer/compose.yaml, .devcontainer/devcontainer.json, README.md, test/dummy/config/database.yml
**Summary:**
Added support for using devcontainers in development.
_N/A_
Added support for using devcontainers in development.
**Testing:**
I spun up the application for each of the database types and made sure I could run `User.first` inside a Rails console.
_N/A_
**Checklist:**
_N/A_
=> Added devcontainer support

docs/4_payment_methods.md, lib/pay/paddle_billing/charge.rb, lib/pay/paddle_billing/payment_method.rb
This PR fixes a bug found in this discussion: https://github.com/pay-rails/pay/discussions/922#discussioncomment-8191211
It also adds a new method called `sync_from_transaction` which takes both a `pay_customer` and a `transaction`. This then uses the Paddle API to grab the details for that transaction and create/update a Payment Method for the given Pay Customer.
```ruby
Pay::PaddleBilling::PaymentMethod.sync_from_transaction pay_customer: Customer.last.payment_processor, transaction: "txn_01hmxtm1ep1c2pznfftybn56kk"
```
=> Fix to Paddle Billing Payment Method creation

lib/pay/stripe/subscription.rb
**Summary:**
Fixes the bug where users cannot unpause a Stripe subscription.
#991
Changed the `pause_collection: ""` instead of `pause_collection: nil` in the `unpause` method of the `Pay::Stripe::Subscription` class so that it can be passed on to Stripe.
=> Fixed unpause stripe subscription empty params bug

lib/pay/stripe/webhooks/subscription_trial_will_end.rb, test/pay/stripe/webhooks/subscription_trial_will_end_test.rb
**Summary:**
To fix an issue where subscription.sync! doesn't pass in `stripe_account` params if Connect.
**Checklist:**
=> [b] Fix: Stripe subscription trial will end webhook event with Connect

lib/pay/fake_processor/billable.rb, test/pay/fake_processor/billable_test.rb
**Summary:**
When using `FakeProcessor`, adding a new `default` payment method does not unset the previous default payment methods, causing the `payment_processor.default_payment_method` method to return an outdated default payment method.
=> Fix: Unset previous default payment methods when adding a new one using FakeProcessor

app/controllers/pay/webhooks/stripe_controller.rb, docs/2_configuration.md, lib/pay/stripe.rb, test/controllers/pay/webhooks/stripe_controller_test.rb, test/pay/stripe_test.rb
**Summary:**
New configuration: STRIPE_WEBHOOK_RECEIVE_TEST_EVENTS (Default to TRUE)
As per the guidance from https://support.stripe.com/questions/connect-account-webhook-configurations: "When a connected account is linked solely in live mode to your platform, both live and test events are sent to your live Connect Webhook Endpoint." Therefore, you can set this to false if you wish to receive only live events in Production.
https://github.com/pay-rails/pay/issues/999
**Checklist:**
=> [f] Stripe webhook - New configuration to control whether you want to receive test events

lib/pay/paddle_billing.rb, lib/pay/stripe.rb
The goal of this PR is to introduce a simple interface for syncing one-time or subscription transactions. For Stripe, this is syncing Checkout Sessions and determining the Charge or Subscription to sync. For Paddle Billing, this retrieves a Transaction and determines if it is a charge or subscription.
We can also take this a step further and provide a method that takes a hash (like `params`) and determines whether to sync from Stripe, Paddle Billing, etc.
The end goal is to provide integrations a single method to call for syncing after checkout.
```ruby
class Checkout::CompletedController < ApplicationController
def show
charge_or_subscription = Pay.sync(params)
redirect_to root_path, notice: "Thanks for your purchase!"
end
end
```
=> Add Paddle Billing and Stripe sync methods

lib/pay/stripe/billable.rb
**Summary:**
Lock the `Pay::Customer` while creating its associated Stripe customer. This is to prevent a race condition where more than one Stripe customers can be created for a single `Pay::Customer`.
See discussion: https://github.com/pay-rails/pay/discussions/857
We have twice now encountered a race condition where more than one Stripe customer was created for a single `Pay::Customer`. This was discovered because of bugs in our React frontend which caused it to accidentally fire multiple API requests to the backend at the same time. Two requests (two threads) would enter the `customer` method at the same time. Both would see that no Stripe customer yet existed and both would begin creating one. The last one to complete would overwrite the previous …
=> Lock Pay::Customer while creating a Stripe customer

docs/1_installation.md
The required version is `~> 12` so this PR updates the docs to say so
=> Update Stripe version in docs

app/models/pay/stripe/subscription.rb, docs/stripe/6_metered_billing.md
**Summary:**
Usage records for usage based billing is now a legacy method in Stripe. Meter events are the new way to track usage: https://docs.stripe.com/api/billing/meter-event?lang=ruby.
I've added a method to make an API call to Stripe to create a meter event. The response from the Stripe SDK is returned to the caller to handle as needed.
**Checklist:**
=> Add support for Stripe's Meter Events for usage based billing

docs/stripe/5_webhooks.md
Pay also handles the `customer.subscription.trial_will_end` event. It should be included in the documentation
=> Add missing stripe webhook event to documentation

app/models/pay/stripe/customer.rb, app/models/pay/stripe/subscription.rb, docs/stripe/6_metered_billing.md
**Summary:**
Following on from https://github.com/pay-rails/pay/pull/1051#discussion_r1735276015, I didn't realise that the `processor_id` in the subscription is the ID for the subscription itself rather than the customer. The API requires the ID to be the customer's rather than the subscription's. Stripe throws an error as it stands.
As such I've moved the method into the `Customer` class as I feel it belongs there.
**Checklist:**
=> Change meter event to use the customer's processor ID

docs/stripe/5_webhooks.md
**Summary:**
Manually setting up a new Stripe webhook and selecting each event is is rather tedious. This makes it a lot easier.
There's no way to copy/paste all the required webhook events into Stripe and enable them in one go. I have made a feature request to Stripe, but in the mean time we can use this trick instead.
When creating a new webhook, I noticed Stripe automatically updates the URL to include each selected event. So I thought: why not provide the full list of events we need and see if those are automatically added when the page is loaded. And guess what, they are!
So we can link to `https://dashboard.stripe.com/webhooks/create?events=comma,separated,list,of,events` and those events will be be pre-selected. Comma's need to URL encoded. (`%2C`). Clicking this …
=> Add link to create Stripe webhook with all the required events

.github/dependabot.yml, .github/workflows/ci.yml
**Summary:**
While browsing this repo source code I have noticed that some GitHub actions versions are outdated.
This PR updates them to the latests version and configures Dependabot to automatically open PRs for them once a month.
=> Update GitHub actions versions

docs/paddle_billing/2_javascript.md
**Summary:**
Update deprecated Paddle.Setup() method to Paddle.Initialize() and minor syntax in Paddle Billing documentation.
I'm integrating Paddle in my service, and noticed that Paddle.js has deprecated the Paddle.Setup() method in favor of Initialize() method: `https://developer.paddle.com/paddlejs/methods/paddle-setup`.
Additionally, quotes are required around the `<%= Pay::PaddleBilling.client_token %>` erb; otherwise I'm running into the following error as it's not read as a string while initializing paddle.js.
=> Update Paddle Billing Javascript Documentation

app/models/pay/paddle_billing/subscription.rb
**Summary:**
While swapping plans / updating quantity for a subscription, allow users to set proration mode for paddle billing.
Currently, proration mode is hardcoded to `prorated_immediately`, but users may choose different proration mode depending on their use case. Ref: https://developer.paddle.com/api-reference/subscriptions/update-subscription.
The implementation in this PR is similar to Stripe's subscription model: https://github.com/pay-rails/pay/blob/main/app/models/pay/stripe/subscription.rb#L277
=> Allow proration mode argument for paddle_billing subscription update

app/models/pay/lemon_squeezy/subscription.rb
**Summary:**
There's a bug in the `Pay::LemonSqueezy::Subscription#sync` method that prevents it from succeding. 
[#1086 
](https://github.com/pay-rails/pay/issues/1086)
Just fixed a simple syntax error that I found while testing subscription flows in a LemonSqueezy environment.
**Testing:**
Tested the changes by switching the gem installation to my branch
Here are the logs that show the successful webhook processing
```
TRANSACTION (0.1ms)  commit transaction
07:40:53 web.1  | [ActiveJob] Enqueued Pay::Webhooks::ProcessJob (Job ID: bc9605ee-b9ce-4189-9137-6fa2d8731b03) to Async(default) with arguments: #<GlobalID:0x0000000140abed98 @uri=#<URI::GID gid://daisy-solid-template/Pay::Webhook/39>>
07:40:53 web.1  | Completed …
```
=> Fix LemonSqueezy sync subscription method

docs/stripe/8_stripe_checkout.md
**Summary:**
I wanted to customize the return url used by Stripe checkout UI:
N/A
The gem allows it, but it's not documented, hence my PR.
[https://github.com/pay-rails/pay/blob/33b8c2e9606dac1ff6c78c2e5bd6ce6f7b2a9b0f/app/models/pay/stripe/customer.rb#L226](https://github.com/pay-rails/pay/blob/33b8c2e9606dac1ff6c78c2e5bd6ce6f7b2a9b0f/app/models/pay/stripe/customer.rb#L226)
**Testing:**
N/A
N/A
**Checklist:**
N/A
=> Enhance Stripe billing portal documentation adding return_url option

docs/stripe/1_overview.md, docs/stripe/7_stripe_tax.md
It seems this was replaced in the 8.0 release, so this should make the docs reflective of that change.
**Summary:**
Updating the docs to match method name changes in a recent release.
Just a simple change to the docs since I happened to be working with this bit of the code for a project.
**Testing:**
Should not be necessary, this is purely a change to the docs.
**Checklist:**
=> Replace outdated update_customer! call in docs

UPGRADE.md, app/models/pay/fake_processor/subscription.rb, test/pay/fake_processor/subscription_test.rb
**Summary:**
Adding `self.sync` to fake processor for API consistency
Currently, the fake processor does not implement `self.sync`, so calling `sync!` if a user is subscribed to a `fake` process (in my case, users whom I gave free access) triggers an error. Ideally, since it does nothing, it should just be a bypass so that clients don't need to check the subscription type before calling the `sync!` or not
Also fixed a couple of typos while going through the upgrade guide. 
**Testing:**
**Checklist:**
=> Adding self.sync to fake processor for a consistent API

lib/pay/stripe/webhooks/payment_action_required.rb, lib/pay/stripe/webhooks/payment_failed.rb, test/pay/stripe/webhooks/payment_action_required_test.rb, test/pay/stripe/webhooks/payment_failed_test.rb
Since incomplete subscriptions are just pending and are currently being created by a customer in the browser, the JavaScript will handle these events. We can safely ignore them server-side and prevent sending duplicates.
Stripe Checkout's payment intents are also only usable inside Checkout, so if they were to be used to complete the charge, they may raise an error.
=> Ignore Stripe failed payment webhooks for incomplete subscriptions

CHANGELOG.md, app/models/pay/stripe/merchant.rb, docs/marketplaces/stripe_connect.md
Updated docs to provide some detail on the default `onboarding_complete` flag that's set based on account verification, and also felt it worth a callout about the gotcha related to Stripe Connect's API updates. Also updated syntax that might have been outdated
=> Update stripe_connect.md to reflect Stripe API changes and offer some color on Merchant#onboarding_complete

app/models/pay/fake_processor/customer.rb, test/pay/fake_processor/customer_test.rb
**Summary:**
Adds `sync_subscriptions` to `FakeProcessor::Customer` to mimic the Stripe processor API.
My code calls `user.payment_processor.sync_subscriptions(status: "all")` with the Stripe processor. In my tests using the fake processor, this method is missing. Returns `[]` to mimic the "map" return type in [the Stripe processor](https://github.com/pay-rails/pay/blob/main/app/models/pay/stripe/customer.rb#L153-L155).
**Testing:**
Added a unit test.
**Checklist:**
=> add sync_subscriptions to FakeProcessor::Customer

lib/pay/attributes.rb, test/pay/attributes_test.rb, test/test_helper.rb
**Summary:**
This adds use of a lock in the `set_payment_processor` to prevent accidentally creating more than one pay_customer for a user if it is called more than once at the same time (from multiple threads).
https://github.com/pay-rails/pay/issues/1158
**Testing:**
**Checklist:**
=> Lock set_payment_processor to prevent accidentally creating multiple pay_customers for a user

app/models/pay/customer.rb, test/pay/customer_test.rb
**Summary:**
Updates the `Pay::Customer#email` method to return `nil` if `owner` has been deleted instead of raising an error:
```
ActiveSupport::DelegationError: email delegated to owner, but owner is nil
```
https://github.com/pay-rails/pay/pull/403
**Testing:**
**Checklist:**
=> Update Pay::Customer#email to return nil if owner has been deleted

app/models/pay/stripe/subscription.rb, app/models/pay/subscription.rb, test/pay/attributes_test.rb, test/pay/braintree/subscription_test.rb
This updates Stripe to sync ends_at from the API response consistently.
Also fixes #1170 where trial_ends_at was set regardless of a trial existing or not.
=> Using cancel_now considers the trial to be ended

lib/pay/attributes.rb
This is a breaking change but it adds the `pay_` prefix to pay model's charge and subscription associations. It's unlikely `payment_processor` methods will conflict, so we're going to leave that as-is for now.
Closes #1167
=> Rename charge and subscription associations to prevent conflicts

app/views/pay/user_mailer/receipt.text.erb
**Summary:**
This was created to address an issue arising from an error we encountered in the latest mailpace gem where there is no safety check for the text part of the email.
This copies over the existing receipt html email to a text version.
=> add text version of receipt mailer

app/views/pay/user_mailer/payment_action_required.text.erb, app/views/pay/user_mailer/payment_failed.text.erb, app/views/pay/user_mailer/refund.text.erb, app/views/pay/user_mailer/subscription_renewing.text.erb, app/views/pay/user_mailer/subscription_trial_ended.text.erb, app/views/pay/user_mailer/subscription_trial_will_end.text.erb, test/mailers/pay/user_mailer_test.rb
**Summary:**
This introduces text versions of all existing user mailers for pay.
Since I recently made a PR for the receipt mailer that was merged it was realized that what would have been the better move would have been to make text versions for all of the mailers thus this PR is now created.
=> Create text versions of existing user mailers

docs/2_configuration.md
**Summary:**
Updates the README with missing mailer configuration options
Since v4 it has been possible to override the parent mailer class, or use a different mailer entirely. Unfortunately these options were not documented outside of the changelog, so I've added them to the README for increased visibility.
=> Update README with missing mailer configuration options

docs/1_installation.md
**Summary:**
I noticed the example gem versions in the installation docs were outdated. Updated the example gems with their latest release version
=> Update gems versions in installation docs

docs/5_charges.md
**Summary:**
This updates the charges docs to use `update_payment_method` instead of the `payment_method_token` virtual attribute which was [removed in 8.0.0](https://github.com/pay-rails/pay/blob/d7b3d7ad749c4624b5357e8264454104179c579c/CHANGELOG.md?plain=1#L173)
=> Update charges docs to use update_payment_method
